// Commonly used keyboard constants
export const ESCAPE = 'Escape';
export const LEFT_ARROW = 'ArrowLeft';
export const UP_ARROW = 'ArrowUp';
export const RIGHT_ARROW = 'ArrowRight';
export const DOWN_ARROW = 'ArrowDown';
export const HOME = 'Home';
export const END = 'End';
export const TAB = 'Tab';
