name: CI

on:
  push:
    branches:
      - 'master'
  pull_request: {}

env:
  node-version: 16.x

jobs:
  verify:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/node_pnpm
        with:
          node-version: ${{ env.node-version }}

      - name: Check commit message
        run: pnpm commitlint --config commitlint.config.cjs --from HEAD~1

      - name: Check format
        run: pnpm format:check

      - name: Lint
        run: pnpm lint

      - name: Check dependencies mismatches
        run: pnpm syncpack list-mismatches

      - name: Unit testing
        run: pnpm test

  playwright:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/node_pnpm
        with:
          node-version: ${{ env.node-version }}

      - name: Install Playwright
        run: pnpx playwright install --with-deps

      - name: Component testing
        run: pnpm --filter=* test-ct
